-- Migration: Add client_id field to blocks table
-- Date: 2025-10-16
-- Purpose: Support temporary client-side IDs for optimistic UI updates

-- Add client_id column
ALTER TABLE blocks 
ADD COLUMN client_id VARCHAR(255) NULL 
COMMENT 'Temporary ID from frontend for block synchronization';

-- Add index for fast lookups
CREATE INDEX idx_blocks_client_id ON blocks(client_id);

-- Note: This field stores the temporary UUID generated by frontend
-- before the block is saved to the database. It allows UpdatePageInline
-- to find blocks even when frontend hasn't yet received the real DB ID.
